import torch
import torch.nn as nn
import numpy as np

class PINNInverse(nn.Module):
    def __init__(self, N_INPUT, N_OUTPUT, N_HIDDEN, mu_init):
        super().__init__()
        # Use Tanh or GELU activations for smooth second derivatives!
        self.net = nn.Sequential(
            nn.Linear(N_INPUT, N_HIDDEN), nn.Tanh(),
            nn.Linear(N_HIDDEN, N_HIDDEN), nn.Tanh(),
            nn.Linear(N_HIDDEN, N_HIDDEN), nn.Tanh(),
            nn.Linear(N_HIDDEN, N_OUTPUT)
        )
        
        # Register mu as an active, trainable parameter for the Inverse Problem
        # Wrapped in a tensor so PyTorch tracks it alongside weights
        self.mu = nn.Parameter(torch.tensor([mu_init], dtype=torch.float32, requires_grad=True))

    def forward(self, t):
        return self.net(t)

    def compute_loss(self, t_data, x_data, t_physics):
        """
        t_data: Sparse time points where we have observations
        x_data: The actual true position coordinates generated by your RK4 script
        t_physics: Collocation time points where we enforce the VDP equation
        """
        # 1. DATA LOSS: Ensure the network passes through your experimental points
        x_pred_data = self.forward(t_data)
        loss_data = torch.mean((x_pred_data - x_data) ** 2)

        # 2. PHYSICS LOSS: Enforce the Van der Pol ODE residual
        # Ensure PyTorch tracks gradients on our physics evaluation timeline
        t_p = t_physics.clone().detach().requires_grad_(True)
        x = self.forward(t_p)

        # Calculate first derivative: dx/dt (Velocity)
        dxdt = torch.autograd.grad(x, t_p, torch.ones_like(x), create_graph=True)[0]
        
        # Calculate second derivative: d2x/dt2 (Acceleration)
        dx2dt2 = torch.autograd.grad(dxdt, t_p, torch.ones_like(dxdt), create_graph=True)[0]

        # --- THE ODE RESIDUAL FORMULA ---
        # d2x/dt2 - mu * (1 - x^2) * dxdt + x = 0
        # Notice we use 'self.mu' here so the optimizer updates it every step!
        physics_residual = dx2dt2 - self.mu * (1.0 - x**2) * dxdt + x
        loss_physics = torch.mean(physics_residual ** 2)

        # Total combined loss
        return loss_data, loss_physics